### PR TITLE
docs(design): add schema for configuration question file

### PR DESCRIPTION
**Pull request by sgoings**
When I eventually port the `rigger configure` step fully over to Go, I'd like to follow the design of having a question file drive the behavior of the configuration walkthrough step. This, to me, seems easier to change in the future and allows us to easily manipulate the fastest route user paths through the configuration step of `rigger`.

Here's a try at specifying the questionfile in .toml format.

### CODE REVIEW

**Comment by smugcloud** [comment]
I like where you're going with this.  It might help to abstract away some of this to make it easier for anyone to get up and running with Deis.  So I was thinking a concise set of core questions:
1.  Choosing the cloud provider to provision (and download/configure those CLI's)
2.  Create an SSH key for the user, but allow for choosing an existing key.
3.  Enter the domain name used to deploy applications
4. Provision and validate

This helps simplify things for anyone looking for a quick version to get started.  Anything more advanced (Kubernetes configs, Deis project forks,  paths on system, different Deis version), can be fed in via optional arguments.  Then we satisfy both ends of the spectrum and this could be used in CI/CD testing.

**Comment by mboersma** [comment]
This PR is seven months old. Should we close it?

**Comment by mboersma** [comment]
This is the most senior PR in the Deis world. 👴  I'm going to close it, but please do re-open if this activity is still in progress.

**Comment by sgoings** [comment]
Ah mannnn. 😜

**Pull request closed without merging**
